mode: rule
log-level: info
proxies:
  - name: HongKong
    type: vmess
    server: 83.229.125.78
    port: 9137
    uuid: 531f9aed-9db3-4f42-9efe-ba76ed9c4627
    alterId: 0
    cipher: auto
proxy-groups: 
  - name: Proxy
    type: select
    proxies:
      - HongKong
      - DIRECT
rules:
  - DOMAIN-SUFFIX,mi.com,DIRECT
  - DOMAIN-SUFFIX,google.com,Proxy
  - DOMAIN-SUFFIX,github.com,Proxy
  - GEOIP,CN,DIRECT
  - MATCH,Proxy