proxies:
  - name: HongKong - Vmiss
    type: vmess
    server: 38.47.108.222
    port: 9137
    uuid: 531f9aed-9db3-4f42-9efe-ba76ed9c4627
    alterId: 0
    cipher: auto
  - name: HongKong - Evoxt
    type: vmess
    server: 108.165.100.202
    port: 9137
    uuid: 531f9aed-9db3-4f42-9efe-ba76ed9c4627
    alterId: 0
    cipher: auto
proxy-groups: 
  - name: Proxy
    type: select
    proxies:
      - HongKong - Vmiss
      - HongKong - Evoxt
