proxies:
  - name: HongKong
    type: vmess
    server: 206.237.13.65
    port: 9137
    uuid: 531f9aed-9db3-4f42-9efe-ba76ed9c4627
    alterId: 0
    cipher: auto
  - name: U.S.A
    type: vless
    server: 147.135.10.103
    port: 443
    uuid: 3b9bc773-05eb-4d5f-8c1f-57342c0c4f40
    skip-cert-verify: true
    network: tcp
    servername: 147135010103.sec19org.com
    tls: true
    udp: true
proxy-groups: 
  - name: Proxy
    type: select
    proxies:
      - HongKong